



try:
    print(number)
except:
    print("Error")

num1 = 7
num2 = 0

try:
    print(num1/num2)
except:
    print("Error")
finally:
    print('Success')